### PR TITLE
Changed some styles to keep the mobile site inside of the viewport, CLA approved

### PR DESCRIPTION
**Pull request by bcromijn**
Did some tweaks to resolve some display issues on the homepage.

image

image

Also some formatting issues in the code, forgotten ;'s and caps where not needed.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/116)

### CODE REVIEW

**Comment by bcromijn** [comment]
I signed it!

**Comment by bcromijn** [comment]
I signed it!

**Comment by tafsiri** [comment]
:lgtm_strong: Thanks for the fix! Looks like there is still a CLA issue though.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-website/116#-:-L9LQiMb2JQ6UCrEZbN-:b-edy9cq)*

**Comment by tafsiri** [comment]
@bcromijn looks like your CLA signing has been updated internally even if the bot doesn't reflect it here, so i'm going to go ahead and merge this.

**Pull request merged**
