### PR TITLE
Drop submodules

### PR DESCRIPTION
**Pull request by tafsiri**
Stop using the git submodule feature to manage the clone of tfjs used to build docs. We no longer have a bunch of different repositories to maintain and the submodule workflow can be complicated. 

Now we just use a regular clone.

This change will generally just require people to do a fresh clone of the website to clean up state.

Closes https://github.com/tensorflow/tfjs/issues/3838

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/375)

### CODE REVIEW

**Comment by tafsiri** [comment]
cc @jinjingforever

**Review by lina128 — APPROVED** [review]
Thank you Yannick! The release process does a fresh clone. The publish process is manual, does it need a fresh clone, or is fetch origin and reset --hard to origin ok? Not sure whether it affects how node_modules are resolved.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/375#-:-MGnuZL1-TEabl1YAFhk:b-n3cb9)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Comment by tafsiri** [comment]
@lina128 what do you mean by manual? Could you give me a quick pointer to the workflow/script you are referring to for publish? If its from the website repo itself (build and release) then this is designed to work with that.

**Comment by lina128** [comment]
Discussed offline, the publish process should work as is.

**Pull request merged**
