### PR TITLE
make getting started more explicit for the two different paths

### PR DESCRIPTION
**Pull request by tafsiri**
This makes the getting started instructions more explicit for the two different workflows of script tag vs npm.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/123)

### CODE REVIEW

**Comment by tafsiri** [comment]
If this looks good i want to do the same thing in the README of tfjs.

**Comment by nsthorat** [comment]
Text LGTM, can you send a screenshot?

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-website/123#-:-L9fGoro6xW7rfs7yJP8:b-jbsf8z)*

**Comment by tafsiri** [comment]
screen shot 2018-04-09 at 12 45 51 pm

**Pull request merged**
