### PR TITLE
Update file paths to match tf.org

### PR DESCRIPTION
**Pull request by lamberta**
stage: go/tfo-stage/js

tf.org style for filenames is to use underscore instead of dashes. This may change one day, but Colab doesnt support dashes and we want the URLs to be consistent.

For relative paths, add file extension to be browseable it GitHub. The import script will automatically remove it.

Rename guides/ to guide/ to be consistent with rest of tf.org

Removed a few gerunds I happen to come across.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/269)

### CODE REVIEW

**Comment by lamberta** [comment]
@tafsiri Thanks

**Comment by lamberta** [comment]
How about "Tensor data structures and operations" ?

Assuming the operations are only applicable to tensors in this doc

**Comment by lamberta** [comment]
Eh, i'll just switch it back to "Tensors and operations"

**Comment by tafsiri** [comment]
@lamberta merged.

**Comment by lamberta** [comment]
thanks!

**Pull request merged**
