### PR TITLE
Add description of file:// save and load in tfjs-node

### PR DESCRIPTION
**Pull request by caisq**
Towards: https://github.com/tensorflow/tfjs/issues/343

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/164)

### CODE REVIEW

**Comment by tafsiri** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[source/tutorials/model-save-load.md, line 200 at r1](https://reviewable.io/reviews/tensorflow/tfjs-website/164#-LEQ_wUv8m7MO5XmBDuT:-LEQ_wUv8m7MO5XmBDuU:btiwd2p) ([raw file](https://github.com/tensorflow/tfjs-website/blob/db026df62703bcc944b1491f508b7d557f01bdc0/source/tutorials/model-save-load.md#L200)):*
> ```Markdown
> ```
> 
> To achieve the latter, you simply serve the files as static files from your
> ```

I'd suggest removing 'you simply'.

---

*[source/tutorials/model-save-load.md, line 201 at r1](https://reviewable.io/reviews/tensorflow/tfjs-website/164#-LEQa9lwEg3GJ0hes3-9:-LEQa9lwEg3GJ0hes3-A:b-5qq0ec) ([raw file](https://github.com/tensorflow/tfjs-website/blob/db026df62703bcc944b1491f508b7d557f01bdc0/source/tutorials/model-save-load.md#L201)):*
> ```Markdown
> 
> To achieve the latter, you simply serve the files as static files from your
> web server. These files can also be converted to the HDF5 format of Python Keras
> ```

This part is a bit confusing to me, i thought the converter converted HDF5 files into the .json and .bin format? In the context of this tutorial it may be unclear why one would want to convert to HDF5. I lean towards removing this sentence, but maybe i just don't understand where you were going with it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/164)*

**Comment by caisq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[source/tutorials/model-save-load.md, line 200 at r1](https://reviewable.io/reviews/tensorflow/tfjs-website/164#-LEQ_wUv8m7MO5XmBDuT:-LESIvmuE0SrD4lyLu9s:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-website/blob/db026df62703bcc944b1491f508b7d557f01bdc0/source/tutorials/model-save-load.md#L200)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

I'd suggest removing 'you simply'.
</blockquote></details>

Done.

---

*[source/tutorials/model-save-load.md, line 201 at r1](https://reviewable.io/reviews/tensorflow/tfjs-website/164#-LEQa9lwEg3GJ0hes3-9:-LESIw2C0pN_FKUie-9M:bwixjk8) ([raw file](https://github.com/tensorflow/tfjs-website/blob/db026df62703bcc944b1491f508b7d557f01bdc0/source/tutorials/model-save-load.md#L201)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

This part is a bit confusing to me, i thought the converter converted HDF5 files into the .json and .bin format? In the context of this tutorial it may be unclear why one would want to convert to HDF5. I lean towards removing this sentence, but maybe i just don't understand where you were going with it.
</blockquote></details>

I reworded this sentence a little to provide motivation for why one would care about tensorflowjs_converter in this case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/164)*

**Comment by tafsiri** [comment]
:lgtm_strong: 

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/164#-:-LEVvGPY4liZoh4WNb7x:b-uwkowd)*

**Comment by nkreeger** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/164#-:-LEWf6Y03KMf2QssYs9t:b-jbsf8z)*

**Pull request merged**
