### PR TITLE
Add Layers subheading: Advanced Activation

### PR DESCRIPTION
**Pull request by caisq**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/111)

### CODE REVIEW

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[source/_data/api/skeleton.json, line 78 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-website/111#-L96c-TWC6CGg0a32a6g:-L96c-TWC6CGg0a32a6h:b-58fdrl) ([raw file](https://github.com/tensorflow/tfjs-website/blob/7287ec79a291a8e046fcc9de21009f1f5755845e/source/_data/api/skeleton.json#L78)):*
> ```JSON
>     "subheadings": [
>       {
>         "name": "Advanced Activation",
> ```

fine for now, but maybe we can consider following keras.io and order this block by use-case: https://keras.io/layers/about-keras-layers/

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-website/111#-:-L96c8qs3okrkuAhwCvs:b-jbsf8z)*

**Comment by tafsiri** [comment]
Just FYI, let me merge this as i want to first double check whether it will show up if the section is empty.

**Comment by tafsiri** [comment]
Also LGTM

**Comment by nsthorat** [comment]
It should show up in the sections if it's not defined, it will be last.

**Pull request merged**
