### PR TITLE
fix: broken_link

### PR DESCRIPTION
**Pull request by chenqing**
in https://www.tensorflow.org/js/tutorials/transfer/what_is_transfer_learning , there has two broken link.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/278)

### CODE REVIEW

**Comment by chenqing** [comment]
done

**Comment by nsthorat** [comment]
You just need to respond with "I signed it" and then the CLA check will pass.

Thanks for the PR!

**Comment by chenqing** [comment]
I signed it

**Comment by chenqing** [comment]
> We found a Contributor License Agreement for you (the sender of this pull request), but were unable to find agreements for all the commit author(s) or Co-authors. If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA ([login here](https://cla.developers.google.com/) to double check)? If these were authored by someone else, then they will need to sign a CLA as well, and confirm that they're okay with these being contributed to Google.
> In order to pass this check, please resolve this problem and have the pull request author add another comment and the bot will run again. If the bot doesn't comment, it means it doesn't think anything has changed.
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Ftensorflow%2Ftfjs-website%2Fpull%2F278) for more info**.

I signed it

**Comment by chenqing** [comment]
> We found a Contributor License Agreement for you (the sender of this pull request), but were unable to find agreements for all the commit author(s) or Co-authors. If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA ([login here](https://cla.developers.google.com/) to double check)? If these were authored by someone else, then they will need to sign a CLA as well, and confirm that they're okay with these being contributed to Google.
> In order to pass this check, please resolve this problem and have the pull request author add another comment and the bot will run again. If the bot doesn't comment, it means it doesn't think anything has changed.
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Ftensorflow%2Ftfjs-website%2Fpull%2F278) for more info**.

I signed it!

**Comment by chenqing** [comment]
I signed it!

**Comment by chenqing** [comment]
I signed it!

**Comment by tafsiri** [comment]
Thanks @chenqing, looks like this change is also included in this PR https://github.com/tensorflow/tfjs-website/pull/279 which fixes another broken link. So i'll merge that one. But thanks for the fix!

**Pull request closed without merging**
