### PR TITLE
Enable customizing tag array and displaying variables

### PR DESCRIPTION
**Pull request by Linchenn**
This PR enables generating tags if a comment contains `doctags` and also adds a template for variables.

For example, for the following codes, API doc will show:
```js
/**
 * Whether we will use shapes uniforms.
 *
 * @doc {heading: 'Flags', subheading: 'WebGL'}
 * @doctags webgl, performance
 */
 export const WEBGL_USE_SHAPES_UNIFORMS = 'WEBGL_USE_SHAPES_UNIFORMS';
```
image

(Parsing flags from tfjs will be in the next PR)

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/477)

### CODE REVIEW

**Review by mattsoulanille — APPROVED** [review]
LGTM. Nice ui!

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/477)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @Linchenn)

___
*[`themes/tfjs/layout/partials/apiFlag.hbs` line 6 at r1](https://reviewable.io/reviews/tensorflow/tfjs-website/477#-NG3HruU96UMVLP4_m2d:-NG3HruU96UMVLP4_m2e:bn7fbee) ([raw file](https://github.com/tensorflow/tfjs-website/blob/b27d431427fa08db5d1df2f8032efcfb4198b824/themes/tfjs/layout/partials/apiFlag.hbs#L6)):*
> ```Handlebars
>       {{~displayName~}}
>     </a>
>     <span class="chip">flag</span>
> ```

discussed offline, the flag chip might not be needed, we could add some other tags, like 'experimental', 'performance', 'correctness', 'webgl', 'wasm', etc

**Review by Linchenn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/477)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[`themes/tfjs/layout/partials/apiFlag.hbs` line 6 at r1](https://reviewable.io/reviews/tensorflow/tfjs-website/477#-NG3HruU96UMVLP4_m2d:-NG3qj_fAEzjhj-Z-BGa:be3y7c3) ([raw file](https://github.com/tensorflow/tfjs-website/blob/14641ceb058fd06fe179ea4b7661b4e01befa8e4/themes/tfjs/layout/partials/apiFlag.hbs#L6)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

discussed offline, the flag chip might not be needed, we could add some other tags, like 'experimental', 'performance', 'correctness', 'webgl', 'wasm', etc
</blockquote></details>

Enabled customizable tag array and updated PR description. Thank you!

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/477)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
