### PR TITLE
Typo: Corrected typo thresohldedReLU -> thresholdedReLU

### PR DESCRIPTION
**Pull request by xam-ps**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/135)

### CODE REVIEW

**Comment by xam-ps** [comment]
See [PR 136 in tfjs-layers](https://github.com/tensorflow/tfjs-layers/pull/136)

**Comment by tafsiri** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---

*[themes/dljs/source/js/vendor/tf.min.js, line 0 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-website/135#-LATn-2h5wlGvBE-PliB:-LATn-2h5wlGvBE-PliC:b-qexzrk) ([raw file](https://github.com/tensorflow/tfjs-website/blob/e60ec72f2539341dd4f8806ccc6b9208e898c9ae/themes/dljs/source/js/vendor/tf.min.js#L0)):*
Thanks @xam-ps! Since this is for an already released version could you remove the tf.min.js from this PR. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-website/135)*

**Comment by xam-ps** [comment]
Done

**Comment by tafsiri** [comment]
:lgtm_strong:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-website/135#-:-LAoJByqBQ24DRsz4mEE:b-jbsf8z)*

**Pull request merged**
