### PR TITLE
Point to new TensorFlow blog

### PR DESCRIPTION
**Pull request by lamberta**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/115)

### CODE REVIEW

**Comment by nsthorat** [comment]
@tafsiri can you review this? Was there a redirect link we wanted to keep?

**Comment by lamberta** [comment]
blog.tensorflow.org is the redirect but https doesn't work: b/77523834
This PR brings the footer in line with tensorflow.org: cl/191326606
The footer link may change to https://blog.tensorflow.org, but, for now, it's fine to directly link to the medium page.

**Comment by nsthorat** [comment]
:lgtm_strong:

Ah got it. Thanks for the links / explanation :)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-website/115#-:-L9IwtVx0D2qYKQuBv-K:b-ad2a8i)*

**Comment by nsthorat** [comment]
& the fix!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-website/115#-:-L9IwzAa4GVcoA2_iPt5:b-kynxxi)*

**Comment by lamberta** [comment]
Thank you!

**Pull request merged**
