### PR TITLE
Add tfjs-data

### PR DESCRIPTION
**Pull request by kangyizhang**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/217)

### CODE REVIEW

**Comment by nsthorat** [comment]
A few comments from looking at your API docs demo:

1. The Creation / Operation subsection should come before the classes, can you pin that?
2. Do we need to show CSVDataset in the docs? Why not just return a regular DataSet (there are no extra methods on that class so it's not very actionable).
3. On the tf.data.DataSet and LazyIterator class you enumerate all the methods on that, but you can tag the methods themself with the doc annotation. This will make it more consistent with the rest of the docs.
4. Nothing in the jsdocs return a LazyIterator, how does one go about making one? Can you make the return type of some method return one of these?
5. The DataSource classes you have seem to be orphans as well, can you remove them or make sure something returns one of these?

BTW, you don't have to call JSON.stringify() anymore in jsdocs: https://github.com/tensorflow/tfjs-website/pull/218

**Comment by kangyizhang** [comment]
1. The Creation / Operation subsection should come before the classes, can you pin that?

Done.

2. Do we need to show CSVDataset in the docs? Why not just return a regular DataSet (there are no extra methods on that class so it's not very actionable).

We don't need it and its jsdoc has been removed.

3. On the tf.data.DataSet and LazyIterator class you enumerate all the methods on that, but you can tag the methods themself with the doc annotation. This will make it more consistent with the rest of the docs.

Done. 

4. Nothing in the jsdocs return a LazyIterator, how does one go about making one? Can you make the return type of some method return one of these?

Also I misunderstood LazyIterator's jsdoc and it has been removed.

5. The DataSource classes you have seem to be orphans as well, can you remove them or make sure something returns one of these?

We don't really need them. Removed.

You can take a look of the website at http://kangyizhang0.mtv.corp.google.com:4000/api/local/#class:data.Dataset

**Comment by tafsiri** [comment]
Comments from looking at the URL you included above.

Structure looks good, so all my comments are about the actual docs themselves.

- For `source` param of `tf.data.csv`, can it also be a file path or would it need to be a file url (if so it would be nice to explicitly say that local files are supported on node).
- `columnConfigs: (Optional) A dictionary whose key is column names, value is an object stating if this column is required, column's data type, default value, and if this column is label. If provided, keys must correspond to names provided in columnNames or inferred from the file header lines.` Doesn't really tell you how to specify these things for a given column (e.g. the key for isRequired, or what the available data types are). I would use some kind of object notation to indicate the schema of a column config.
- `tf.data.zip`, does it take any iterable? If so i would say, it takes an array object or iterable (rather than "nested data structure" as its harder to picture what you mean by that). I think this one would benefit from more code snippets. E.g. to demonstrate zipping two objects together. Overall i'm not sure what kinds of things can be zipped or how the underlying datasets should look and i think it would be easier to demonstrate with code snippets than describe.
- It would be nice to have an example of mapAsync or explanation of when to use this over map. Also if your map function returns a promise would that cause a problem?
- batch, may be nice to split the batching of objects into its own code snippet. its a lot to take in.
- It would be great to see tf.data.array used with fitDataset (e.g. how to do xs and ys get passed in together)

**Comment by kangyizhang** [comment]
(1) `source` param of tf.data.csv could only be a file url currently. The modules to support local file is ready and I had a PR working on it. And reading large local file as stream in node is top ranking feature that will be worked on next.

(2) `CSVConfig` better formatted in 

(3) `tf.data.zip` does not take iterable. The param should be a container of datasets, e.g. an array of datasets or a dict whose values are datasets. The datasets could be come from iterables. Added an example of zipp a dict of datasets. 

(4) '.mapAsync()' added an example. The only difference is that whether the user's function is sync/async.

(5) `.batch()` spit code snippets into three sections.

(6) `tf.data.array` is a light weight `Dataset` creation api which is intended to be used for testing `Dataset` object. We intended not to show user about creating `Dataset` with `tf.data.array` without training part, unlike `tf.data.csv`. Also the training part, usage of `model.fitDataset`, is exactly the same no matter how the `Dataset` is created.

**Comment by tafsiri** [comment]
@kangyizhang thanks. Ping me on chat when you re-generate this with a new version of union. Note that you should remove the generated files for 0.14.0 from this.

**Pull request merged**
