### PR TITLE
A browser playground proposal

### PR DESCRIPTION
**Pull request by tafsiri**
Using codepen, the new Try it button

screen shot 2018-04-11 at 5 41 14 pm

Would open

screen shot 2018-04-11 at 5 31 29 pm

Ready for people to edit and save to their own codepen accounts should they choose to.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-website/128)

### CODE REVIEW

**Comment by dsmilkov** [comment]
:lgtm_strong: This is pretty sweet

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[themes/dljs/helper/index.js, line 86 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-website/128#-L9qrjPp0ebHBxuxnMx0:-L9qrjPp0ebHBxuxnMx1:b-hniolj) ([raw file](https://github.com/tensorflow/tfjs-website/blob/c954c42f4e928bc999b6d4cfd0341cde1b294c84/themes/dljs/helper/index.js#L86)):*
> ```JavaScript
>   model.predict(tf.tensor2d([5], [1, 1])).print();
> });
> `);
> ```

add 6 spaces (align this with the return JSON.stringify)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-website/128#-:-L9qrvB51xq30e-X5asy:br5plhp)*

**Comment by tafsiri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[themes/dljs/helper/index.js, line 86 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-website/128#-L9qrjPp0ebHBxuxnMx0:-L9u53NZ2jJryQdMaKIO:b-ag5as9) ([raw file](https://github.com/tensorflow/tfjs-website/blob/c954c42f4e928bc999b6d4cfd0341cde1b294c84/themes/dljs/helper/index.js#L86)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

add 6 spaces (align this with the return JSON.stringify)
</blockquote></details>

Sorry,, i should have added a comment, the weird indentation is to control what it looks like on codepen. Indenting here will indent extra on codepen (i'll add a comment).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-website/128)*

**Comment by nsthorat** [comment]
Okay so I totally thought this was for docs originally.

Quick question, why not just use the editable / runnable snippet stuff on the homepage? I'm fine either way, just curious.

**Comment by tafsiri** [comment]
@nsthorat i'd say this is orthogonal to making that front page snippet runnable (it just uses the same code as a starting point—so that we don't have too many starter snippets out there). This provides a more full featured 'playground' environment for browser development. Visitors can develop fairly extensive projects in codepen without having to download anything.

**Comment by nsthorat** [comment]
SGTM

**Pull request merged**
